### ISSUE TITLE
Add cargo-deny to CI to check licenses and crate sources

### ISSUE THREAD

**Issue by brycx** [brycx/orion#146]
Running `cargo deny check` will, based on `deny.toml` in the crate root, check for advisories, allowed licenses and sources for dependencies.

A sensible configuration probably looks somewhat like so (see the [example here](https://github.com/EmbarkStudios/cargo-deny/blob/main/deny.toml)):

```toml
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"
vulnerability = "deny"

[licenses]
unlicensed = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "MIT",
    "BSD-3-Clause",
    "Apache-2.0",
]

[bans]
multiple-versions = "allow" # We don't maintain Cargo lockfile, so this isn't really feasible to deny
wildcards = "deny" # Dependencies should not have be specified with '*'

[sources]
unknown-registry = "deny" # crates.io is allowed and a known register by default
unknown-git = "deny"
```

(IANAL) Regarding the allowed licenses, based on the below resources I believe they can be combined and therefor can be allowed. Explicitly stating allowed licenses can helps us avoid accidentally adding dependencies which aren't compatible with each other.

In terms of denying unknown registries and git sources, this is to ensure that any dependency added can be audited at any point, and we are aware of it's origin.

There's also a [GH Action](https://embarkstudios.github.io/cargo-deny/index.html#github-action) for this.

Ref: 
- https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
- https://janelia-flyem.github.io/licenses.html
- https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences
